name: Deployment Workflow

on:
  push:
    branches:
      - main

jobs:
  common-tasks:
    uses: ./.github/workflows/common-tasks.yml  # Reference the reusable workflow

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: common-tasks  # Ensure this runs after common-tasks
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build the project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
